name: Test
concurrency: production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm' # Cache npm dependencies

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests (test:unit)
        run: npm run test:unit

      - name: Run End-to-End Tests (test:e2e)
        run: npm run test:e2e

      - name: Run Playwright Tests with Report Generation
        run: npx playwright test --reporter=html --output=playwright-report

      - name: Display test results (Playwright HTML Report)
        if: failure() # This step runs only if the tests fail
        run: cat ./playwright-report/index.html || echo "No Playwright test results file found"
