name: Test
concurrency: production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start application
        run: npm start &
        env:
          PORT: 3030

      - name: Wait for application to be ready
        run: npx wait-on http://localhost:3030

      - name: Run Unit Tests (test:unit)
        run: npm run test:unit

      - name: Run End-to-End Tests (test:e2e)
        run: npm run test:e2e

      - name: Run Playwright Tests with Report Generation
        run: npx playwright test --reporter=html --output=playwright-report

      - name: Coverage badges generation action
        uses: jpb06/coverage-badges-action@v1.0.13

      - name: Stop server
        run: killall node
